#############################################################################
# Makefile for building: daveplusplus
# Generated by qmake (2.00a) (Qt 4.1.1) on: Tue Apr 25 17:03:24 2006
# Project:  daveplusplus.pro
# Template: subdirs
# Command: /usr/bin/qmake -unix -o Makefile daveplusplus.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src

src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src/" || $(MKDIR) "src/"
	cd src && $(QMAKE) src.pro -unix -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) "src/" || $(MKDIR) "src/"
	cd src && $(QMAKE) src.pro -unix -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src/$(MAKEFILE) FORCE
	cd src && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src/$(MAKEFILE) FORCE
	cd src && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src/$(MAKEFILE) FORCE
	cd src && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src/$(MAKEFILE) FORCE
	cd src && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src/$(MAKEFILE) FORCE
	cd src && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src/$(MAKEFILE) FORCE
	cd src && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src/$(MAKEFILE) FORCE
	cd src && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: daveplusplus.pro  /usr/share/doc/qt-4.1.1/mkspecs/linux-g++/qmake.conf /usr/share/doc/qt-4.1.1/mkspecs/qconfig.pri \
		/usr/share/doc/qt-4.1.1/mkspecs/features/qt_config.prf \
		/usr/share/doc/qt-4.1.1/mkspecs/features/exclusive_builds.prf \
		/usr/share/doc/qt-4.1.1/mkspecs/features/default_pre.prf \
		/usr/share/doc/qt-4.1.1/mkspecs/features/debug.prf \
		/usr/share/doc/qt-4.1.1/mkspecs/features/default_post.prf
	$(QMAKE) -unix -o Makefile daveplusplus.pro
/usr/share/doc/qt-4.1.1/mkspecs/qconfig.pri:
/usr/share/doc/qt-4.1.1/mkspecs/features/qt_config.prf:
/usr/share/doc/qt-4.1.1/mkspecs/features/exclusive_builds.prf:
/usr/share/doc/qt-4.1.1/mkspecs/features/default_pre.prf:
/usr/share/doc/qt-4.1.1/mkspecs/features/debug.prf:
/usr/share/doc/qt-4.1.1/mkspecs/features/default_post.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile daveplusplus.pro

qmake_all: sub-src-qmake_all FORCE

make_default: sub-src-make_default FORCE
make_first: sub-src-make_first FORCE
all: sub-src-all FORCE
clean: sub-src-clean FORCE
distclean: sub-src-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

